### ISSUE TITLE
OpenNI error when samples are executed 

### ISSUE THREAD

**Issue by BigPuncho** [jmendeth/PyOpenNI#61]
Hello, I sucessfully installed everything, at least I didn't get any errors, but when I try to run any of the examples I get this kind of error in all of them:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 540, in runfile
    execfile(filename, namespace)
  File "/home/andre/OpenNI/PyOpenNI/examples/hand-tracker.py", line 9, in <module>
    depth_generator.create(context)
<class 'openni.OpenNIError'>: Can't create any node of the requested type!

Am I missing something important, or did the lib not compile correctly?

**Comment by jmendeth** [comment]
Do OpenNI official examples work?

**Comment by BigPuncho** [comment]
Yes they do, I can only guess it's the PyOpenNI compilation that went wrong

**Comment by jmendeth** [comment]
That doesn't seem to be the case. This example usually means that:

 - No sensors are plugged in or accessible from your current user.
 - You have no sensor drivers for the sensors that are plugged in. (i.e. OpenNI on itself is not able to talk to a Kinect, you need SensorKinect too).

But you say the official examples did work, so I don't know.
It's a long time since I last used OpenNI, it's now dead because Apple acquired PrimeSense.

**Comment by BigPuncho** [comment]
I'll try to repeat the process on another computer and see if it persists

**Comment by BigPuncho** [comment]
It's working now, must have been a dependency.

**Comment by jmendeth** [comment]
Hmm, did you accidentally doubleclick?

**Comment by BigPuncho** [comment]
Do you mean the "Close issue" button? No, I closed but then opened it again in case you wanted to ask something. But can close it if you have nothing to add.

**Comment by jmendeth** [comment]
I have nothing to add for now...
